# Generated by Django 5.0.3 on 2024-03-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='is_varified',
        ),
    ]
